### ISSUE TITLE
"Error writing back to client"

### ISSUE THREAD

**Issue by RonRN18** [librespeed/speedtest-go#38] opened 2022-02-07 23:34 UTC
## Description
My speedtest server appears to work but I'm seeing errors; I'd like to understand the errors and learn if there is anything that can be improved.

## Server
I have created a VM on an XCP-ng hypervisor. This VM is running Ubuntu 21.10. I have Go version go1.17.6 installed. I have created a Systemd service to start the speedtest binary file. In my settings, I have set my port to be port 80. I have set HAProxy to redirect [speedtest.webbnet.org](http://speedtest.webbnet.org) to run the speedtest.

## Client
It appears to work on my Windows 11 Pro laptop with Edge, Chrome, and Firefox.
I have problems with my iPhone 11 Pro Max with iOS 15.4 in both Safari and Chrome. The initial page pops up and the test gets the ping and jitter, but then fails as it is trying to do the actual speedtest.

Below is a sample of what I'm seeing in my syslog file:
`Feb  7 15:05:56 go speedtest[10610]: time="2022-02-07T15:05:56-08:00" level=error msg="Error writing back to client at chunk number 1: write tcp 192.168.20.82:80->192.168.20.1:1111: write: connection reset by peer"
Feb  7 15:05:56 go speedtest[10610]: time="2022-02-07T15:05:56-08:00" level=error msg="Error writing back to client at chunk number 6: write tcp 192.168.20.82:80->192.168.20.1:1093: write: connection reset by peer"
Feb  7 15:05:56 go speedtest[10610]: time="2022-02-07T15:05:56-08:00" level=error msg="Error writing back to client at chunk number 1: write tcp 192.168.20.82:80->192.168.20.1:1112: write: connection reset by peer"
`

**Comment by blu006** [comment] 2022-05-06 04:55
I am also having similar issues with the version tagged as v1.1.4.

**Comment by maddie** [comment] 2022-07-08 17:10
This is not application related in most cases. The `connection reset by peer` and `broken pipe` errors are mostly caused by the other side closing the connection prematurely.

**Closed by maddie** 2022-07-08 17:10 UTC
